development: 
  host: 'localhost'
  adapter: 'postgresql'
  database: 'week-six-howlr'
  encoding: 'utf8'
  pool: 5
test: 
  host: 'localhost'
  adapter: 'postgresql'
  database: 'week-six-howlr-test'
  encoding: 'utf8'
  pool: 5
